"""
Integration test configuration.

Prerequisites:
1. Start LiteLLM: docker compose up -d litellm postgres-litellm
2. Run setup: make litellm_setup
3. Set in .env:
   - OPENAI_API_KEY (required by LiteLLM proxy)
   - LITELLM_BASE_URL=http://localhost:4000
   - LITELLM_TEST_KEY (generated by setup script)

Tests will fail with KeyError if environment variables are missing.
"""

import os
import pytest_asyncio
from api.dependencies import service_container
from api.config import settings


@pytest_asyncio.fixture(scope="session", autouse=True)
async def initialize_service_container():
    """
    Initialize service container for integration tests.

    Note: ASGI transport doesn't trigger FastAPI lifespan events, so we
    manually initialize the service container here.

    IMPORTANT: Override LITELLM_API_KEY to use TEST key for all integration tests.
    This ensures test usage is tracked separately from dev/prod usage.
    """
    # Override settings.llm_api_key to use test key
    # Settings object is created at import time, so we must modify it directly
    settings.llm_api_key = os.environ["LITELLM_TEST_KEY"]

    await service_container.initialize()

    yield

    # Cleanup - ignore event loop closed errors (common pytest-asyncio issue)
    try:
        await service_container.cleanup()
    except RuntimeError as e:
        if "Event loop is closed" not in str(e):
            raise
