# MCP Servers Configuration for Docker Compose
# This file configures MCP server connections for containerized deployment

servers:
  # Fake MCP Server (for demos and testing)
  - name: fake-mcp-server
    url: http://fake-mcp-server:8001/mcp/
    enabled: true
    description: "Demo MCP server with fake tools for testing"
    
  # Example: Add more MCP servers here as you build them
  # - name: web-search-server
  #   url: http://web-search-server:8002/mcp/
  #   enabled: true
  #   auth_env_var: WEB_SEARCH_API_KEY
  #   description: "Web search MCP server"
  
  # - name: database-server
  #   url: http://database-server:8003/mcp/
  #   enabled: true
  #   auth_env_var: DATABASE_CONNECTION_STRING
  #   description: "Database operations MCP server"
  
  # - name: filesystem-server
  #   url: http://filesystem-server:8004/mcp/
  #   enabled: true
  #   description: "File system operations MCP server"
