# MCP Configuration for demo_complete.py
# This config enables the demo MCP server with fake tools

servers:
  - name: demo_tools
    url: http://localhost:8001/mcp/
    enabled: true
    # This server provides realistic fake tools:
    # - get_weather: Weather information for any location
    # - search_web: Web search with realistic results
    # - get_stock_price: Stock market data
    # - analyze_text: Text sentiment analysis
    # - translate_text: Language translation
    # Start with: uv run python mcp_servers/fake_server.py